### ISSUE TITLE
Configuração de CORS

### ISSUE THREAD

**Issue by Naldo100** [B2W-BIT/restQL-http#110]
A ideia é disponibilizar na ferramenta uma opção de configuração de CORS com possibilidade de passar variáveis de ambiente.

**Comment by lucasbarros** [comment]
Atualmente o handler de `OPTIONS` não implementa nenhuma restrição, podemos adicionar as configurações padrões e customizar pelo `env` ou `yml`.

https://github.com/B2W-BIT/restQL-http/blob/497fc23f9663ef8032850b1c2f412028f46c1d63/src/clojure/restql/http/server/handler.clj#L35

Padrões sugeridos:
- `Access-Control-Allow-Origin`: "*"
- `Access-Control-Allow-Methods`: "GET, POST, PUT, PATH, DELETE, OPTIONS"
- `Access-Control-Allow-Headers`: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
- `Access-Control-Expose-Headers`: "Content-Length,Content-Range"

Env:
```sh
CORS_ALLOW_ORIGIN=${allowed_custom_origin}
CORS_ALLOW_METHODS=${allowed_custom_methods}
CORS_ALLOW_HEADERS=${allowed_custom_headers}
CORS_EXPOSE_HEADERS=${allowed_custom_expose_headers}
```

Yml:
```yml
cors:
    allow_origin: ${allowed_custom_origin}
    allow_methods: ${allowed_custom_methods}
    allow_headers: ${allowed_custom_headers}
    expose_headers: ${allowed_custom_expose_headers}
```
